PREFIX cis: <http://dati.beniculturali.it/cis/>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT *
WHERE {
  ?s a cis:CulturalInstituteOrSite .
  ?s rdfs:label ?label .
  OPTIONAL { ?s dc:type ?type . }
  OPTIONAL { ?s rdfs:comment ?comment . }
  OPTIONAL { ?s cis:identifier ?id . }
  OPTIONAL { ?s geo:long ?long . ?s geo:lat ?lat . }
  OPTIONAL { ?s owl:sameAs ?owl . }
  OPTIONAL { ?s rdfs:seeAlso ?seeAlso . }
  OPTIONAL { ?s cis:hasDiscipline ?hasDiscipline . }
  OPTIONAL {
    ?s cis:hasContactPoint ?hasContactPoint .
    OPTIONAL { ?hasContactPoint cis:hasTelephone ?telephone . }
    OPTIONAL { ?hasContactPoint cis:hasEmail ?email . }
    OPTIONAL { ?hasContactPoint cis:hasFax ?fax . }
    OPTIONAL { ?hasContactPoint cis:hasWebsite ?website . }
    OPTIONAL { ?hasContactPoint cis:hasCertifiedEmail ?pec . } 
  }

  OPTIONAL { ?s cis:providesService ?providesService . }

  OPTIONAL { ?s cis:hasAccessCondition ?hasAccessCondition . }
  OPTIONAL { ?s cis:hasNameInTime ?hasNameInTime . }

  OPTIONAL { ?s cis:hasTicket ?hasTicket . }
  ?s cis:hasSite ?sede .
}
